### ISSUE TITLE
Can't Start; alive_progresss Module issu

### ISSUE THREAD

**Issue by 2B-4G10** [Alfredredbird/tookie-osint#48]
**Describe the bug**

Alfred is starting...
/home/kali/alfred/alfred/__main__.py
Traceback (most recent call last):
  File "/home/kali/alfred/brib.py", line 15, in <module>
    from alive_progress import *
ModuleNotFoundError: No module named 'alive_progress'

**Comment by LincolnKermit** [comment]
What version of Python do you have?
Try to reinstall the modules by typing : `pip3 install -r requirements.txt`

**Comment by Alfredredbird** [comment]
Hello. Alfred is made for python 3.12. some people have got 3.11 working but its mainly 12. Assuming you have python3.12, you can fix the above error with `pip3.12 install alive_progress` or `pip3.12 install -r requirements.txt`. feel free to let me know if you need anything else. :D

**Comment by Alfredredbird** [comment]
> What version of Python do you have? Try to reinstall the modules by typing : `pip3 install -r requirements.txt`

yes that should work

**Comment by Alfredredbird** [comment]
im going to close this thread
