### ISSUE TITLE
Problem - First Use

### ISSUE THREAD

**Issue by OrangUranKlaus** [Alfredredbird/tookie-osint#56]
Hi Boys,

I'm very interested in your project, but I'm not a big Linux/Python professional. I get the following error message while the first usage. Can you help me?

Check for updates? [Y/n]: ⤷ Y
Update or reinstall? [U/r]: U
Traceback (most recent call last):
  File "/home/XXX/tookie-osint/brib.py", line 91, in <module>
    configUpdateStuff(colorScheme, config, browser, language_module, argument)
  File "/home/XXX/tookie-osint/modules/configcheck.py", line 161, in configUpdateStuff
    ask_update_check(config, colorScheme, language_module)
  File "/home/XXX/tookie-osint/modules/configcheck.py", line 121, in ask_update_check
    exec(open("./update.py").read())
  File "<string>", line 102, in <module>
  File "<string>", line 19, in __init__
NameError: name 'config_version_path' is not defined

Thanks a lot

**Comment by Alfredredbird** [comment]
Hey, Sorry to hear that you are having trouble. Ill look into fixing it soon if you can give me some details.

**I will need the following info:**

Tookie OSINT version [Version Info](https://github.com/Alfredredbird/tookie-osint/wiki/Versions)
Python version.
OS Running on.

~ Thanks :D

**Comment by OrangUranKlaus** [comment]
Thanks for youre quick reply.

Im using Ubuntu 22.04.3 WSL Linux 5.15.153.1-microsoft-standard-WSL2 (i did a fresh install) and Python 3.10.12 and Tookie OSINT v2.6(a)

When i use tookie-osint without the update check it seems to work fine.

**Comment by Alfredredbird** [comment]
> Thanks for youre quick reply.
> 
> 
> 
> Im using Ubuntu 22.04.3 WSL Linux 5.15.153.1-microsoft-standard-WSL2 (i did a fresh install) and Python 3.10.12 and Tookie OSINT v2.6(a)
> 
> 
> 
> When i use tookie-osint without the update check it seems to work fine.

Hey, thanks for the info. I will fix this issue as soon as possible. For the meanwhile, I'd advise you to use Python 3.12 instead of 3.10. Also v2.6(a) is the latest version, so you should be good for a while. 

Sorry for the inconvenience.
