### ISSUE TITLE
Fehlermeldung 

### ISSUE THREAD

**Issue by FranzWaismayer** [Alfredredbird/tookie-osint#57]
Ich habe tookie-osint nach Vorgabe installiert.
Bei Verwendung bekomme ich nachfolgende Fehlermeldung:
![tookie-osint](https://github.com/Alfredredbird/tookie-osint/assets/79380033/d8db1b1a-e1e4-4751-9810-cd9815370984)

Was kann die Ursache sein?

**Comment by Alfredredbird** [comment]
Please install the "selenium" package and it should be fixed.

`pip3.12 install selenium`

~ Hope that helps :D

**Comment by FranzWaismayer** [comment]
leider nicht
das Paket selenium wurde erfolgreich installiert, aber es bleibt die selbe fehlermeldung

**Comment by Alfredredbird** [comment]
> leider nicht
> 
> das Paket selenium wurde erfolgreich installiert, aber es bleibt die selbe fehlermeldung

Oh I see. What Python version do you have? If you have more then one, then you must install it with the correct version number. 

Example:

pip3.12 install selenium 
pip3.10 install selenium

Tookie OSINT is deciding to run itself with a different Python version.

**Comment by FranzWaismayer** [comment]
Es wurde dir richtige Version sprich 3.12 installiert

**Comment by Alfredredbird** [comment]
> Es wurde dir richtige Version sprich 3.12 installiert
> 
> 

That's good. The "no module named selenium found" is generally caused by it not being installed. 

Maybe try the following to open a Python editor and see if you get any errors:

`python3.12`
`import selenium`

**Comment by FranzWaismayer** [comment]
leider noch immer nicht

**Comment by Alfredredbird** [comment]
dang. are you installing selenium as sudo? if so, try without or try the following:

`pip3.12 uninstall selenium`
`pip3.12 install selenium`

then close your terminal and reopen it.

**Comment by FranzWaismayer** [comment]
leider keine Änderung
