### ISSUE TITLE
module error when install 

### ISSUE THREAD

**Issue by Mrpolack** [Alfredredbird/tookie-osint#60]
Hi, it gives me an errpr wotj flask_

Using cached selenium-4.23.1-py3-none-any.whl (9.4 MB)
Using cached trio_websocket-0.11.1-py3-none-any.whl (17 kB)
Installing collected packages: alive_progress, Flask, trio-websocket, selenium
  Attempting uninstall: Flask
    Found existing installation: Flask 3.0.3
error: uninstall-no-record-file

× Cannot uninstall Flask 3.0.3
╰─> The package's contents are unknown: no RECORD file was found for Flask.

hint: The package was installed by debian. You should check if it can uninstall the package.
                                                                                                                           
┌──(kali㉿kali)-[~/tookie-osint]
└─$ python3 tookie-osint
tookie-osint is starting...
/home/kali/tookie-osint/tookie-osint/__main__.py
Traceback (most recent call last):
  File "/home/kali/tookie-osint/brib.py", line 21, in <module>
    from modules.configcheck import *
  File "/home/kali/tookie-osint/modules/configcheck.py", line 13, in <module>
    from modules.webscrape import *
  File "/home/kali/tookie-osint/modules/webscrape.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

**Comment by Alfredredbird** [comment]
Hey, sorry about your issue. Please install the selenium package via pip. 'pip3 install selenium'. Let me know if it works. ❤️
