### ISSUE TITLE
False information

### ISSUE THREAD

**Issue by Quelnan** [Alfredredbird/tookie-osint#64]
**Describe the bug**
I tried to osint myself but there was so many sites that im not logged on
like pypi or scratch 

**To Reproduce**
1. Open tools
2. Osint yourself
3. You will see sites that you dont even logged on and the sites will be 404

**Expected behavior**
Sites that im logged on

**Screenshots**
![image](https://github.com/user-attachments/assets/2f592124-6cc6-4fff-a339-cb2461f51166)

**Desktop (please complete the following information):**
 - OS: Kali Linux
 - VM: Virtual Box
 - Real OS: Windows 10
 - Browser: It said it will use chrome
 - Version: Last version

**Additional context**
Most of the sites (that im not logged on) will return 404 page

**Comment by Alfredredbird** [comment]
> **Describe the bug**
> 
> I tried to osint myself but there was so many sites that im not logged on
> 
> like pypi or scratch 
> 
> 
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> 1. Open tools
> 
> 2. Osint yourself
> 
> 3. You will see sites that you dont even logged on and the sites will be 404
> 
> 
> 
> **Expected behavior**
> 
> Sites that im logged on
> 
> 
> 
> **Screenshots**
> 
> ![image](https://github.com/user-attachments/assets/2f592124-6cc6-4fff-a339-cb2461f51166)
> 
> 
> 
> **Desktop (please complete the following information):**
> 
>  - OS: Kali Linux
> 
>  - VM: Virtual Box
> 
>  - Real OS: Windows 10
> 
>  - Browser: It said it will use chrome
> 
>  - Version: Last version
> 
> 
> 
> **Additional context**
> 
> Most of the sites (that im not logged on) will return 404 page
> 
> 

Hello Quelnan, thanks for your wonderful report! As you might know, some sites might return a false positive. However, I'm currently trying to figure out why it's displaying sites with a `404' error. I've noticed that VM's seem to have issues. What attack modes did you use? 

🦜
