### ISSUE TITLE
Does anyone know how to help?

### ISSUE THREAD

**Issue by theperfectprotagonist** [Alfredredbird/tookie-osint#65]
Beginner here. While installing I came across an error and I'm wondering if anyone knows a solution any help would grateful. It comes when i put in the line "python3 tookie-osint". I'm using a command prompt window and have python installed on it but idk
![Screenshot 2024-12-09 203506](https://github.com/user-attachments/assets/3de472aa-1c01-4923-89ab-32114bf33c80)

**Comment by DrAnonym666** [comment]
pip install alive-progress

https://pypi.org/project/alive-progress/

**Comment by theperfectprotagonist** [comment]
Thank you so much I'll try later.

**Comment by Alfredredbird** [comment]
> pip install alive-progress
> 
> 
> 
> https://pypi.org/project/alive-progress/

This should the answer. If you have issues with it, try `pip3 install alive-progress`

**Comment by theperfectprotagonist** [comment]
Thank you so much!!
